name: boilerplate
description: "Flutter Boilerplate"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  dio: ^5.4.1
  url_launcher: ^6.3.0
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  get_storage: ^2.1.1
  logger: ^2.3.0
  equatable: ^2.0.5
  easy_localization: ^3.0.7
  provider: ^6.1.2
  path_provider: any
  firebase_core: ^2.31.1
  smooth_page_indicator: ^1.1.0
  get_it: ^7.7.0
  json_theme_plus: ^6.6.1
  loading_overlay: ^0.3.0
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/
    - assets/devImages/
    - assets/images/
    - assets/theme/

fonts:
  - family: Schyler
    fonts:
      - asset: fonts/Schyler-Regular.ttf
      - asset: fonts/Schyler-Italic.ttf
        style: italic
  - family: Trajan Pro
    fonts:
      - asset: fonts/TrajanPro.ttf
      - asset: fonts/TrajanPro_Bold.ttf
        weight: 700

# Please insert background.png, logo_wht.png and logo_trs.png inside assets/images to generate assets
# run command: flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "ic_launcher"
  ios: "AppIcon"
  image_path: "assets/devImages/logo.png"
  min_sdk_android: 24
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/devImages/logo.png"

#run command: dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/devImages/logo.png
  image_dark: assets/devImages/logo.png
  icon_background_color: "#FFFFFF"
  icon_background_color_dark: "#FFFFFF"

  android_12:
    image: assets/devImages/logo.png
    image_dark: assets/devImages/logo.png
    color: "#FFFFFF"
    color_dark: "#000000"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"
  fullscreen: true