name: boilerplate
description: "Flutter Boilerplate"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  url_launcher: ^6.3.0
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  get_storage: ^2.1.1
  logger: ^2.3.0
  equatable: ^2.0.5
  easy_localization: ^3.0.7
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/localization/translations/

fonts:
 - family: Schyler
   fonts:
     - asset: fonts/Schyler-Regular.ttf
     - asset: fonts/Schyler-Italic.ttf
       style: italic
 - family: Trajan Pro
   fonts:
     - asset: fonts/TrajanPro.ttf
     - asset: fonts/TrajanPro_Bold.ttf
       weight: 700
